# Generated by Django 4.1.3 on 2022-12-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0008_publisher_remove_book_pub_book_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub',
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(to='bookstore.book'),
        ),
        migrations.AlterModelTable(
            name='publisher',
            table='publisher',
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
